expense jenkins pipeline

diff --git a/80-cdn/Jenkinsfile b/80-cdn/Jenkinsfile
--- a/80-cdn/Jenkinsfile
+++ b/80-cdn/Jenkinsfile
@@ -1,8 +1,8 @@
 pipeline {
     agent {
-        label 'agent-1'
+        label 'AGENT-1'
     }
-    options {
+    options{
         timeout(time: 30, unit: 'MINUTES')
         disableConcurrentBuilds()
         ansiColor('xterm')
@@ -10,10 +10,9 @@ pipeline {
     // environment {
     //     DEBUG = 'true'
     // }
-    parameters {
-        
-        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action') 
 
+    parameters {
+        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Select Action')
     }
     stages {
         stage('Init and Plan') {
@@ -21,7 +20,7 @@ pipeline {
                 withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                     sh """
                         cd 80-cdn
-                        terraform init --reconfigure
+                        terraform init -reconfigure
                         terraform plan -out=tfplan
                     """
                 }
@@ -29,11 +28,10 @@ pipeline {
         }
 
         stage('Apply or Destroy') {
-            // input {
-            //     message "Should we continue to ${params.ACTION}?"
-            //     ok "Yes, we should."
-            // }
-
+            /* input {
+                message "Should we continue to ${params.ACTION}"
+                ok "Yes, we should."
+            } */
             steps {
                 withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                     sh """
@@ -41,16 +39,13 @@ pipeline {
                         if [ ${params.ACTION} == 'apply' ]
                         then
                             terraform apply -auto-approve tfplan
-                        elif [ ${params.ACTION} == 'destroy' ]
-                        then
-                            terraform destroy -auto-approve
                         fi
                     """
                 }
             }
         }
 
-        stage('Parallel-1') {
+        /* stage('Destroy') {
             when {
                 expression { params.ACTION == 'destroy' }
             }
@@ -65,48 +60,77 @@ pipeline {
                         build job: '60-alb', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                     }
                 }
+                stage('EKS') {
+                    steps {
+                        build job: '40-eks', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
+                    }
+                }
+                stage('Bastion') {
+                    steps {
+                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                    }
+                }
+
+            }
+        } */
+        stage('Destroy'){
+            when {
+                expression { params.ACTION == 'destroy' }
+            }
+            steps{
+                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
+                    script {
+                        def directories = ['80-cdn', '70-ecr', '60-alb', '50-acm', '40-eks', '30-rds', '20-bastion', '10-sg', '00-vpc']
+                        for (dir in directories) {
+                            echo "Destroying resources in directory: ${dir}"
+                            sh """
+                            cd ${dir}
+                            terraform init -reconfigure
+                            terraform destroy -auto-approve || { echo "Failed to destroy resources in ${dir}"; exit 1; }
+                            cd ..
+                            """
+                        }
+            }
+                }
+            }
+        }
+        /* stage('Sequential') {
+            when {
+                expression { params.ACTION == 'destroy' }
+            }
+            stages {
+                
                 stage('ACM') {
                     steps {
                         build job: '50-acm', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                     }
                 }
-                stage('EKS') {
+                stage('SG-Destroy'){
                     steps {
-                        build job: '40-eks', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
+                        build job: '10-sg', parameters: [string(name: 'ACTION', value: "destroy")], wait: true
                     }
                 }
-                stage('Bastion') {
+                stage('VPC-Destroy'){
                     steps {
-                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: "apply")], wait: false
+                        build job: '00-vpc', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
                     }
                 }
             }
-        }
-
-        stage('SG destroy') {
-            steps {
-                build job: '10-sg', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
-            }
-        }
-
-        stage('VPC destroy') {
-            steps {
-                build job: '00-vpc', parameters: [string(name: 'ACTION', value: "destroy")], wait: false
-            }
-        }
+                
+        } */
         
     }
 
     post {
         always{
-            echo "This section runs always"
+            echo "This sections runs always"
             deleteDir()
         }
         success{
-            echo "This section runs when pipeline success"
+            echo "This section run when pipeline success"
         }
         failure{
-            echo "This section runs when pipeline failure"
+            echo "This section run when pipeline failure"
         }
     }
 }
